backbone-require test
Fails with errors:

  1) backbone-requirejs main.js:
     AssertionError: Expr has no type
Expr:    Backbone
At:      /home/sqs/src/tern-integration-tests/groups/backbone-requirejs/main.js:29 [Identifier]
      at /home/sqs/src/tern-integration-tests/test.js:64:9
      at Object.exports.withContext
(/home/sqs/src/tern/lib/infer.js:618:18)
      at /home/sqs/src/tern-integration-tests/test.js:55:13
      at Array.1 (/home/sqs/src/tern-integration-
tests/node_modules/astannotate/astannotate.js:14:7)
      at /home/sqs/src/tern-integration-
tests/node_modules/astannotate/astannotate.js:43:18
      at Context.<anonymous> (/home/sqs/src/tern-integration-
tests/test.js:77:46)
      at Test.Runnable.run
(/usr/lib/node_modules/mocha/lib/runnable.js:194:15)
      at Runner.runTest
(/usr/lib/node_modules/mocha/lib/runner.js:352:10)
      at /usr/lib/node_modules/mocha/lib/runner.js:398:12
      at next (/usr/lib/node_modules/mocha/lib/runner.js:278:14)
      at /usr/lib/node_modules/mocha/lib/runner.js:287:7
      at next (/usr/lib/node_modules/mocha/lib/runner.js:234:23)
      at Object._onImmediate
(/usr/lib/node_modules/mocha/lib/runner.js:255:5)
      at processImmediate [as _immediateCallback] (timers.js:330:15)

  2) backbone-requirejs models.js:
     AssertionError: Expr has no type
Expr:    Person
At:      /home/sqs/src/tern-integration-tests/groups/backbone-requirejs/models.js:14 [Identifier]
      at /home/sqs/src/tern-integration-tests/test.js:64:9
      at Object.exports.withContext
(/home/sqs/src/tern/lib/infer.js:618:18)
      at /home/sqs/src/tern-integration-tests/test.js:55:13
      at Array.1 (/home/sqs/src/tern-integration-
tests/node_modules/astannotate/astannotate.js:14:7)
      at /home/sqs/src/tern-integration-
tests/node_modules/astannotate/astannotate.js:43:18
      at Context.<anonymous> (/home/sqs/src/tern-integration-
tests/test.js:77:46)
      at Test.Runnable.run
(/usr/lib/node_modules/mocha/lib/runnable.js:194:15)
      at Runner.runTest
(/usr/lib/node_modules/mocha/lib/runner.js:352:10)
      at /usr/lib/node_modules/mocha/lib/runner.js:398:12
      at next (/usr/lib/node_modules/mocha/lib/runner.js:278:14)
      at /usr/lib/node_modules/mocha/lib/runner.js:287:7
      at next (/usr/lib/node_modules/mocha/lib/runner.js:234:23)
      at Object._onImmediate
(/usr/lib/node_modules/mocha/lib/runner.js:255:5)
      at processImmediate [as _immediateCallback] (timers.js:330:15)