Testing framework; backbone-sample-app test group
Tests currently fail because tern does not yet handle the 'fullName' property (or likesIceCream, but we don't test for that yet).

  1) backbone-sample-app model.js:
     AssertionError: Expr is missing properties
Expr:    exports.alice
At:      /home/sqs/src/tern-integration-tests/groups/backbone-sample-app/model.js:11 [MemberExpression]
Missing: fullName
All:     <i> _changing _pending _previousAttributes _validate addFriend attributes bind changed changed changedAttributes cid clear clone constructor defaults destroy escape fetch get has hasChanged hasOwnProperty id idAttribute initialize isNew isValid off on once parse previous previousAttributes propertyIsEnumerable save set stopListening sync toJSON toLocaleString toString trigger unbind unset url validationError validationError valueOf